# Form implementation generated from reading ui file 'GUIMenu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import subprocess
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QCoreApplication
from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout, QWidget, QLabel, QLineEdit, QGridLayout, QMessageBox, QStackedWidget, QSizePolicy, QHBoxLayout
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtGui import QIcon, QPixmap, QMovie
from PyQt6.QtGui import QFont


class Ui_MainWindow(object):
         
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 678)
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Icon_only = QtWidgets.QWidget(parent=self.centralwidget)
        self.Icon_only.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    text-align:center;\n"
"    height:30px;\n"
"    border:none;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.Icon_only.setObjectName("Icon_only")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Icon_only)
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.Icon_only)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icons8-customer-50.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TutorialC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.TutorialC.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons8-teach-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.TutorialC.setIcon(icon)
        self.TutorialC.setCheckable(True)
        self.TutorialC.setAutoExclusive(True)
        self.TutorialC.setObjectName("TutorialC")
        self.verticalLayout.addWidget(self.TutorialC)
        self.FreeC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.FreeC.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/pngtree-sign-language-line-icon-vector-png-image_6682775.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.FreeC.setIcon(icon1)
        self.FreeC.setCheckable(True)
        self.FreeC.setAutoExclusive(True)
        self.FreeC.setObjectName("FreeC")
        self.verticalLayout.addWidget(self.FreeC)
        self.QuizC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.QuizC.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons8-quiz-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.QuizC.setIcon(icon2)
        self.QuizC.setCheckable(True)
        self.QuizC.setAutoExclusive(True)
        self.QuizC.setObjectName("QuizC")
        self.verticalLayout.addWidget(self.QuizC)
        self.CaliC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.CaliC.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons8-customer-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CaliC.setIcon(icon3)
        self.CaliC.setCheckable(True)
        self.CaliC.setAutoExclusive(True)
        self.CaliC.setObjectName("CaliC")
        self.verticalLayout.addWidget(self.CaliC)
        self.ContactC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.ContactC.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons8-about-us-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ContactC.setIcon(icon4)
        self.ContactC.setCheckable(True)
        self.ContactC.setAutoExclusive(True)
        self.ContactC.setObjectName("ContactC")
        self.verticalLayout.addWidget(self.ContactC)
        self.TipsC = QtWidgets.QPushButton(parent=self.Icon_only)
        self.TipsC.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons8-lightbulb-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.TipsC.setIcon(icon5)
        self.TipsC.setCheckable(True)
        self.TipsC.setAutoExclusive(True)
        self.TipsC.setObjectName("TipsC")
        self.verticalLayout.addWidget(self.TipsC)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.Icon_only)
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons8-power-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.gridLayout.addWidget(self.Icon_only, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu = QtWidgets.QPushButton(parent=self.widget)
        self.menu.setStyleSheet("border:none;")
        self.menu.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icons8-menu-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu.setIcon(icon7)
        self.menu.setCheckable(True)
        self.menu.setObjectName("menu")
        self.horizontalLayout_3.addWidget(self.menu)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"text-align:center;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/ASLearning.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Tutorial_Page = QtWidgets.QWidget()
        self.Tutorial_Page.setObjectName("Tutorial_Page")
        self.label_8 = QtWidgets.QLabel(parent=self.Tutorial_Page)
        self.label_8.setGeometry(QtCore.QRect(150, 160, 111, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(parent=self.Tutorial_Page)
        self.comboBox.setGeometry(QtCore.QRect(70, 430, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentTextChanged.connect(self.update_text)
        self.Tutorial_Start = QtWidgets.QPushButton(parent=self.Tutorial_Page)
        self.Tutorial_Start.clicked.connect(self.run_module)
        self.Tutorial_Start.setGeometry(QtCore.QRect(180, 430, 111, 61))
        self.Tutorial_Start.setCheckable(False)
        self.Tutorial_Start.setAutoExclusive(False)
        self.Tutorial_Start.setObjectName("Tutorial_Start")
        self.progressBar = QtWidgets.QProgressBar(parent=self.Tutorial_Page)
        self.progressBar.setGeometry(QtCore.QRect(40, 540, 661, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.stackedWidget.addWidget(self.Tutorial_Page)
        self.Free_Page = QtWidgets.QWidget()
        self.Free_Page.setObjectName("Free_Page")
        self.label_11 = QtWidgets.QLabel(parent=self.Free_Page)
        self.label_11.setGeometry(QtCore.QRect(330, 230, 49, 16))
        self.label_11.setObjectName("label_11")
        self.Free_Start = QtWidgets.QPushButton(parent=self.Free_Page)
        self.Free_Start.setGeometry(QtCore.QRect(290, 480, 111, 61))
        self.Free_Start.setCheckable(False)
        self.Free_Start.setAutoExclusive(False)
        self.Free_Start.setObjectName("Free_Start")
        self.stackedWidget.addWidget(self.Free_Page)
        self.Quiz_Page = QtWidgets.QWidget()
        self.Quiz_Page.setObjectName("Quiz_Page")
        self.label_12 = QtWidgets.QLabel(parent=self.Quiz_Page)
        self.label_12.setGeometry(QtCore.QRect(310, 180, 49, 16))
        self.label_12.setObjectName("label_12")
        self.Quiz_Start = QtWidgets.QPushButton(parent=self.Quiz_Page)
        self.Quiz_Start.setGeometry(QtCore.QRect(300, 490, 111, 61))
        self.Quiz_Start.setCheckable(False)
        self.Quiz_Start.setAutoExclusive(False)
        self.Quiz_Start.setObjectName("Quiz_Start")
        self.stackedWidget.addWidget(self.Quiz_Page)


        self.Cali_Page = QtWidgets.QWidget()
        self.Cali_Page.setObjectName("Cali_Page")
        self.label_6 = QtWidgets.QLabel(parent=self.Cali_Page)
        self.label_6.setGeometry(QtCore.QRect(210, 80, 49, 16))
        self.label_6.setObjectName("label_6")
        self.Calibrate_Start = QtWidgets.QPushButton(parent=self.Cali_Page)
        self.Calibrate_Start.setGeometry(QtCore.QRect(300, 430, 111, 61))
        self.Calibrate_Start.setCheckable(False)
        self.Calibrate_Start.setAutoExclusive(False)
        self.Calibrate_Start.setObjectName("Calibrate_Start")
        self.stackedWidget.addWidget(self.Cali_Page)



        self.Contact_Page = QtWidgets.QWidget()
        self.Contact_Page.setObjectName("Contact_Page")
        #self.label_7 = QtWidgets.QLabel(parent=self.Contact_Page)
        #self.label_7.setGeometry(QtCore.QRect(470, 180, 49, 16))
        #self.label_7.setObjectName("label_7")


        self.pic_label1 = QLabel(self.Contact_Page)
        self.pic_label1.setGeometry(185,0,325,225)
        pixmap = QPixmap("src/images/all3_contact_us.jpeg")
        self.pic_label1.setPixmap(pixmap)
        self.pic_label1.setScaledContents(True)

        layout = QVBoxLayout(self.Contact_Page)

        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)

        text_label1 = QLabel("Meet the Founders", self.Contact_Page)
        text_label1.setFont(font1)
        text_label1.setGeometry(255, 240, 200, 25)
        self.Contact_Page.setLayout(layout)

        font2_Contact = QFont()
        font2_Contact.setPointSize(13)

        font3_Contact = QFont()
        font3_Contact.setPointSize(10)
        font3_Contact.setItalic(True)

        #Dan's contact and picture
        self.pic_label2 = QLabel(self.Contact_Page)
        self.pic_label2.setGeometry(50, 300, 125, 125)
        pixmap = QPixmap("src/images/dan_headshot.jpeg")
        self.pic_label2.setPixmap(pixmap)
        self.pic_label2.setScaledContents(True)

        text_label2 = QLabel("Dan Clapp", self.Contact_Page)
        text_label2.setFont(font2_Contact)
        text_label2.setGeometry(70, 430, 200, 25)
        self.Contact_Page.setLayout(layout)

        text_label3 = QLabel("clappd1@wit.edu",self.Contact_Page)
        text_label3.setFont(font3_Contact)
        text_label3.setGeometry(55, 450, 220, 25)
        self.Contact_Page.setLayout(layout)


        #Yass's contact and picture
        self.pic_label3 = QLabel(self.Contact_Page)
        self.pic_label3.setGeometry(290, 300, 125, 125)
        pixmap = QPixmap("src/images/yasmina_headshot.jpeg")
        self.pic_label3.setPixmap(pixmap)
        self.pic_label3.setScaledContents(True)

        text_label5 = QLabel("Yasmina Habchi", self.Contact_Page)
        text_label5.setFont(font2_Contact)
        text_label5.setGeometry(295, 430, 200, 25)
        self.Contact_Page.setLayout(layout)

        text_label6 = QLabel("habchiy@wit.edu",self.Contact_Page)
        text_label6.setFont(font3_Contact)
        text_label6.setGeometry(305, 450, 220, 25)
        self.Contact_Page.setLayout(layout)

      


        #Liam's contact and picture
        self.pic_label4 = QLabel(self.Contact_Page)
        self.pic_label4.setGeometry(505, 300, 125, 125)
        pixmap = QPixmap("src/images/liam_headshot.jpeg")
        self.pic_label4.setPixmap(pixmap)
        self.pic_label4.setScaledContents(True)

        text_label8 = QLabel("Liam Nasr", self.Contact_Page)
        text_label8.setFont(font2_Contact)
        text_label8.setGeometry(530, 430, 200, 25)
        self.Contact_Page.setLayout(layout)

        text_label9 = QLabel("nasrl@wit.edu",self.Contact_Page)
        text_label9.setFont(font3_Contact)
        text_label9.setGeometry(527, 450, 220, 25)
        self.Contact_Page.setLayout(layout)



        self.stackedWidget.addWidget(self.Contact_Page)
        #self.Tips_Page = QtWidgets.QWidget()
        #self.Tips_Page.setObjectName("Tips_Page")
        #self.label_9 = QtWidgets.QLabel(parent=self.Tips_Page)
        #self.label_9.setGeometry(QtCore.QRect(270, 140, 49, 16))
        #self.label_9.setObjectName("label_9")
        #self.stackedWidget.addWidget(self.Tips_Page)

        self.Tips_Page = QWidget()
        self.Tips_Page.setObjectName(u"Tips_Page")
        self.TipsForASL = QLabel(self.Tips_Page)
        self.TipsForASL.setObjectName(u"TipsForASL")
        self.TipsForASL.setGeometry(QtCore.QRect(20, 20, 421, 41))
        font2_Tips = QFont()
        font2_Tips.setPointSize(20)
        font2_Tips.setBold(True)
        self.TipsForASL.setFont(font2_Tips)
        self.TipsForASL.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        gif_width = 180
        gif_height = 180

        self.label = QLabel(self.Tips_Page)
        self.movie = QMovie(self.Tips_Page)
        self.label.setGeometry(321,10,gif_width,gif_height)
        self.movie = QMovie("src/images/youre welcome yas.gif")
        self.movie.setScaledSize(self.label.size())
        self.label.setMovie(self.movie)
        self.movie.start()
        #self.setFixedSize(self.movie.frameRect().width()+400, self.movie.frameRect().height()+400)

        self.verticalLayoutWidget = QWidget(self.Tips_Page)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 200, 701, 421))
        self.TipsLineup = QVBoxLayout(self.verticalLayoutWidget)
        self.TipsLineup.setSpacing(0)
        self.TipsLineup.setObjectName(u"TipsLineup")
        self.TipsLineup.setContentsMargins(0, 0, 0, 0)
        self.Tip1 = QLabel(self.verticalLayoutWidget)
        self.Tip1.setObjectName(u"Tip1")
        font3_Tips = QFont()
        font3_Tips.setPointSize(11)
        font3_Tips.setBold(True)
        self.Tip1.setFont(font3_Tips)
        self.Tip1.setWordWrap(True)

        self.TipsLineup.addWidget(self.Tip1)

        self.Tip2 = QLabel(self.verticalLayoutWidget)
        self.Tip2.setObjectName(u"Tip2")
        self.Tip2.setFont(font3_Tips)
        self.Tip2.setWordWrap(True)

        self.TipsLineup.addWidget(self.Tip2)

        self.Tip3 = QLabel(self.verticalLayoutWidget)
        self.Tip3.setObjectName(u"Tip3")
        self.Tip3.setFont(font3_Tips)
        self.Tip3.setWordWrap(True)

        self.TipsLineup.addWidget(self.Tip3)

        self.Tip5 = QLabel(self.verticalLayoutWidget)
        self.Tip5.setObjectName(u"Tip5")
        self.Tip5.setFont(font3_Tips)
        self.Tip5.setWordWrap(True)

        self.TipsLineup.addWidget(self.Tip5)

        self.Tip4 = QLabel(self.verticalLayoutWidget)
        self.Tip4.setObjectName(u"Tip4")
        self.Tip4.setFont(font3_Tips)
        self.Tip4.setWordWrap(True)

        self.TipsLineup.addWidget(self.Tip4)

        self.stackedWidget.addWidget(self.Tips_Page)

        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.Icon_name = QtWidgets.QWidget(parent=self.centralwidget)
        self.Icon_name.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    text-align:left;\n"
"    height:30px;\n"
"    border:none;\n"
"    padding-left:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.Icon_name.setObjectName("Icon_name")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Icon_name)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.Icon_name)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/icons8-customer-50.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.Icon_name)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TutorialO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.TutorialO.setIcon(icon)
        self.TutorialO.setCheckable(True)
        self.TutorialO.setAutoExclusive(True)
        self.TutorialO.setObjectName("TutorialO")
        self.verticalLayout_2.addWidget(self.TutorialO)
        self.FreeO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.FreeO.setIcon(icon1)
        self.FreeO.setCheckable(True)
        self.FreeO.setAutoExclusive(True)
        self.FreeO.setObjectName("FreeO")
        self.verticalLayout_2.addWidget(self.FreeO)
        self.QuizO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.QuizO.setIcon(icon2)
        self.QuizO.setCheckable(True)
        self.QuizO.setAutoExclusive(True)
        self.QuizO.setObjectName("QuizO")
        self.verticalLayout_2.addWidget(self.QuizO)
        self.CaliO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.CaliO.setIcon(icon3)
        self.CaliO.setCheckable(True)
        self.CaliO.setAutoExclusive(True)
        self.CaliO.setObjectName("CaliO")
        self.verticalLayout_2.addWidget(self.CaliO)
        self.ContactO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.ContactO.setIcon(icon4)
        self.ContactO.setCheckable(True)
        self.ContactO.setAutoExclusive(True)
        self.ContactO.setObjectName("ContactO")
        self.verticalLayout_2.addWidget(self.ContactO)
        self.TipsO = QtWidgets.QPushButton(parent=self.Icon_name)
        self.TipsO.setIcon(icon5)
        self.TipsO.setCheckable(True)
        self.TipsO.setAutoExclusive(True)
        self.TipsO.setObjectName("TipsO")
        self.verticalLayout_2.addWidget(self.TipsO)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.Icon_name)
        self.pushButton_11.setIcon(icon6)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.gridLayout.addWidget(self.Icon_name, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.menu.toggled['bool'].connect(self.Icon_only.setHidden) # type: ignore
        self.menu.toggled['bool'].connect(self.Icon_name.setVisible) # type: ignore
        self.TipsC.toggled['bool'].connect(self.TipsO.setChecked) # type: ignore
        self.ContactC.toggled['bool'].connect(self.ContactO.setChecked) # type: ignore
        self.CaliC.toggled['bool'].connect(self.CaliO.setChecked) # type: ignore
        self.CaliO.toggled['bool'].connect(self.CaliC.setChecked) # type: ignore
        self.ContactO.toggled['bool'].connect(self.ContactC.setChecked) # type: ignore
        self.TipsO.toggled['bool'].connect(self.TipsC.setChecked) # type: ignore
        self.pushButton_6.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton_11.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.TutorialO.toggled['bool'].connect(self.TutorialC.setChecked) # type: ignore
        self.TutorialC.toggled['bool'].connect(self.TutorialO.setChecked) # type: ignore
        self.FreeC.toggled['bool'].connect(self.FreeO.setChecked) # type: ignore
        self.FreeO.toggled['bool'].connect(self.FreeC.setChecked) # type: ignore
        self.QuizO.toggled['bool'].connect(self.QuizC.setChecked) # type: ignore
        self.QuizC.toggled['bool'].connect(self.QuizO.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Welcome to ASLearning!"))
        self.label_8.setText(_translate("MainWindow", "Tutorial Page"))
        self.comboBox.setItemText(0, _translate("MainWindow", "A"))
        self.comboBox.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "C"))
        self.comboBox.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox.setItemText(4, _translate("MainWindow", "E"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox.setItemText(6, _translate("MainWindow", "G"))
        self.comboBox.setItemText(7, _translate("MainWindow", "H"))
        self.comboBox.setItemText(8, _translate("MainWindow", "I"))
        self.comboBox.setItemText(9, _translate("MainWindow", "J"))
        self.comboBox.setItemText(10, _translate("MainWindow", "K"))
        self.comboBox.setItemText(11, _translate("MainWindow", "L"))
        self.comboBox.setItemText(12, _translate("MainWindow", "M"))
        self.comboBox.setItemText(13, _translate("MainWindow", "N"))
        self.comboBox.setItemText(14, _translate("MainWindow", "O"))
        self.comboBox.setItemText(15, _translate("MainWindow", "P"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Q"))
        self.comboBox.setItemText(17, _translate("MainWindow", "R"))
        self.comboBox.setItemText(18, _translate("MainWindow", "S"))
        self.comboBox.setItemText(19, _translate("MainWindow", "T"))
        self.comboBox.setItemText(20, _translate("MainWindow", "U"))
        self.comboBox.setItemText(21, _translate("MainWindow", "V"))
        self.comboBox.setItemText(22, _translate("MainWindow", "W"))
        self.comboBox.setItemText(23, _translate("MainWindow", "X"))
        self.comboBox.setItemText(24, _translate("MainWindow", "Y"))
        self.comboBox.setItemText(25, _translate("MainWindow", "Z"))
        self.Tutorial_Start.setText(_translate("MainWindow", "START!"))
        self.label_11.setText(_translate("MainWindow", "Free Mode"))
        self.Free_Start.setText(_translate("MainWindow", "START!"))
        self.label_12.setText(_translate("MainWindow", "Quiz Page"))
        self.Quiz_Start.setText(_translate("MainWindow", "START!"))
        self.label_6.setText(_translate("MainWindow", "Cali_Page"))
        self.Calibrate_Start.setText(_translate("MainWindow", "Calibrate"))
        #self.label_7.setText(_translate("MainWindow", "Contact_Page"))



        #self.label_9.setText(_translate("MainWindow", "Tips"))


        self.TipsForASL.setText(QCoreApplication.translate("MainWindow", u" Tips for ASL: ", None))
        self.Tip1.setText(QCoreApplication.translate("MainWindow", u"1. Practice Regularly: Consistent practice helps you remember and improve your signing skills. That includes watching others and learning from native signers by observing and mimicking to improve accuracy and fluency.", None))
        self.Tip2.setText(QCoreApplication.translate("MainWindow", u"2. Relax your Hands: Relaxing your hands means that you\u2019re able to sign at a greater speed, with more clarity, and for longer. Be clear with your form.", None))
        self.Tip3.setText(QCoreApplication.translate("MainWindow", u"3. Focus on Facial Expressions: They are a great and crucial tool to use when it comes to communicationin by conveying tone and emotion in ASL.", None))
        self.Tip5.setText(QCoreApplication.translate("MainWindow", u"4. Be clear in your form: Keeping your form in check is a considerate way to ensure that your message is completely understood by the end receiver. The dominant hand does most of the signing, while the non-dominant hand supports.", None))
        self.Tip4.setText(QCoreApplication.translate("MainWindow", u"5. Practice on camera: That's why ASLearning is here for! Recording yourself signing on camera is an effective way to pick up on the points of weakness in your technique which you or others may have not noticed otherwise.", None))



        self.label_3.setText(_translate("MainWindow", "Options"))
        self.TutorialO.setText(_translate("MainWindow", "Tutorial"))
        self.FreeO.setText(_translate("MainWindow", "Free Mode"))
        self.QuizO.setText(_translate("MainWindow", "Quiz"))
        self.CaliO.setText(_translate("MainWindow", "Calibrate"))
        self.ContactO.setText(_translate("MainWindow", "Contact Us"))
        self.TipsO.setText(_translate("MainWindow", "Tips"))
        self.pushButton_11.setText(_translate("MainWindow", "Sign out"))
    
    def run_module(self):
        subprocess.Popen([sys.executable, r"src/learn_modules.py", self.currentLetter.lower()])
    def update_text(self):
        self.currentLetter = self.comboBox.currentText()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
